use L_UNIVER

select PULPIT.PULPIT_NAME,PULPIT.FACULTY
FROM  PULPIT INNER JOIN FACULTY
ON PULPIT.FACULTY=FACULTY.FACULTY 
 AND
FACULTY.FACULTY IN(SELECT FACULTY FROM PROFESSION WHERE(PROFESSION_NAME LIKE '%технология%' or PROFESSION_NAME LIKE '%технологии%' ))

SELECT PULPIT.PULPIT_NAME,PULPIT.FACULTY
FROM PULPIT,FACULTY
WHERE PULPIT.FACULTY=FACULTY.FACULTY AND
FACULTY.FACULTY IN(SELECT FACULTY FROM PROFESSION WHERE(PROFESSION_NAME LIKE '%технология%' or PROFESSION_NAME LIKE '%технологии%' ))

select PULPIT.PULPIT_NAME,PULPIT.FACULTY
FROM  PULPIT INNER JOIN FACULTY
ON PULPIT.FACULTY=FACULTY.FACULTY 
INNER JOIN PROFESSION
ON FACULTY.FACULTY=PROFESSION.FACULTY WHERE(PROFESSION_NAME LIKE '%технология%' or PROFESSION_NAME LIKE '%технологии%' )

Select  top(1)
(select max(AUDITORIUM_CAPACITY) from AUDITORIUM where AUDITORIUM_TYPE like 'ЛК' ) [ЛК],
(select max(AUDITORIUM_CAPACITY) from AUDITORIUM where AUDITORIUM_TYPE like 'ЛК-К')[ЛК-К],
(select max(AUDITORIUM_CAPACITY) from AUDITORIUM where AUDITORIUM_TYPE like 'ЛБ-К' )[ЛБ-К]
from AUDITORIUM

--4 спооб 2
Select AUDITORIUM.AUDITORIUM_TYPE, max(AUDITORIUM_CAPACITY)[максимум] from AUDITORIUM 
Where AUDITORIUM_TYPE IN (Select AUDITORIUM_TYPE from AUDITORIUM) group by AUDITORIUM_TYPE

--5
SELECT FACULTY_NAME  FROM  FACULTY f
WHERE  NOT EXISTS (SELECT * FROM PULPIT p
WHERE p.FACULTY = f.FACULTY)

--6 три некоррелированных подзапроса в списке SELECT
SELECT 
(SELECT AVG (NOTE) FROM PROGRESS
WHERE [SUBJECT] LIKE 'ОАиП')[ОАиП],
(SELECT AVG (NOTE) FROM PROGRESS
WHERE [SUBJECT] LIKE 'СУБД')[СУБД],
(SELECT AVG (NOTE) FROM PROGRESS
WHERE [SUBJECT] LIKE 'ОАиП')[БД] 

--7 (>= больше каждого)
SELECT [SUBJECT], NOTE FROM PROGRESS
WHERE NOTE >= ALL (SELECT NOTE FROM PROGRESS
WHERE [SUBJECT] LIKE '%ОАиП%')

--8 если хотя бы одно значение "истина", то вся операция (> any) принимает значение "истина"
 SELECT [SUBJECT], NOTE FROM PROGRESS
WHERE NOTE > ANY (SELECT NOTE FROM PROGRESS
 WHERE [SUBJECT] LIKE '%БД%');

 --9 ОТДЕЛЬНЫЙ СКРИПТ

 --10*        ВЫБОР СТУДЕНТОВ С ОДИНАКОВОЙ ДАТОЙ РОЖДЕНИЯ 
 SELECT NAME[ИМЯ], BDAY[ДЕНЬ РОЖДЕНИЯ] FROM STUDENT stud1
WHERE exists (SELECT NAME FROM STUDENT stud2 
WHERE stud1.BDAY = stud2.BDAY and stud1.IDSTUDENT <> stud2.IDSTUDENT)
ORDER BY BDAY;

